### PR TITLE
Persist Keys in NSUserDefaults

### PR DESCRIPTION
**Pull request by dylankbuckley**
Pretty crude. But it works.

### CODE REVIEW

**Comment by thomashorrobin** [comment]
brilliant, NSUserDefaults is exactly what we need lol. This makes things much cleaner imo.

I have stumbled into an issue when running it for the first time though:

image

Personally my view is that we should check that accountId and accessToken are in NSUserDefaults and then if they're not we should show the window asking for credentials. What do you think of this?

Also, after this I think we should do a small refactor so that we only start polling the api after we have valid credentials. My general view is that this is a good citizen things to do for users on mobile data and also as a user of Monzo's api. What do you think?

**Comment by dylankbuckley** [comment]
Yeah agree. Interestingly it's not failing for me even after first run...

**Comment by thomashorrobin** [comment]
So I presume that's because once you have a string in there, even if it's empty, it's still able to unwrap it. But new users will have a nil, so ! opperator will error when it tries to read the value. (my understanding of Swift isn't that good so this might be wrong)

**Comment by dylankbuckley** [comment]
You’re correct. I just can’t figure out why I am not getting that error. 

Actually I do know. Its because the keys persist across builds.

**Comment by dylankbuckley** [comment]
Test it now @thomashorrobin just did a quick check on the nsdefaults so hopefully that catches before crash.

**Review by thomashorrobin — COMMENTED** [review]
Boom, working perfectly for new users

**Pull request merged**
